work in progress, commit for safety
rcbsukcesja/wavvy pull request #49
Opened 2023-12-20 02:14 UTC by rafalfuz

2023-12-20 02:15 UTC, rafalfuz commented
NIE MERGOWAC!!!

2023-12-22 15:31 UTC, wojky requested changes

2023-12-22 15:31 UTC, wojky commented on web/src/app/features/companies/companies-list.page.component.ts
> +      <app-list-shell class="flex flex-col grow" *ngIf="state.loadListCallState === 'LOADED'" listName="MŚP" [list]="state.list">
daj na początek ngIfy, od razu widać że element jest warunkowo wyświetlany

2023-12-22 15:31 UTC, wojky commented on web/src/app/features/ngo/ngo-details.page.component.ts
> +                        <div class="mb-4 w-80 h-80 flex flex-col justify-center items-center flex-grow">
formatowanie się rozjechało

2023-12-22 15:31 UTC, wojky commented on web/src/app/features/offers/manage-offers.page.component.ts
> +  <div class="flex flex-col min-h-[calc(100vh-152px)]">
dodawanie elementu często się powtarza, może warto to na dorzucić jako jakiś wrapper komponent albo dyrektywa?

2023-12-22 15:31 UTC, wojky commented on web/src/app/shared/ui/common-contact-dialog.component.ts
> +      <table>
na tabeli? 🤔

2023-12-24 00:30 UTC, merged